fix: use partner details on getuigen/succes
frameless/utrecht-huwelijksplanner pull request #385
Opened 2023-05-27 23:11 UTC by bddjong

Small fix to use correct partner details. This is not a perfect solution, as we should eventually check to get the partner details of whoever is not currently logged in, but for the MVP this makes sense as we are assuming users are doing this together and the logged in user has not changed.

2023-06-05 12:34 UTC, Yolijn requested changes
Looking good! Only suggestions are to destructure `voornaam` and allow for the firstname to be empty and give a better message to the end-user then

2023-06-05 12:34 UTC, Yolijn commented on pages/voorgenomen-huwelijk/getuigen/succes.tsx
> +  const partnerContact = marriageOptions.partners[0]?.contact;
```suggestion
  const { voornaam } = marriageOptions.partners[0]?.contact;
```

2023-06-05 12:34 UTC, Yolijn commented on pages/voorgenomen-huwelijk/getuigen/succes.tsx
> +                  <DataNoTranslate>{partnerContact?.voornaam}</DataNoTranslate> heeft met DigID ingelogd. Nu kunnen
```suggestion
                  { voornaam && <DataNoTranslate>{voornaam}</DataNoTranslate> heeft met DigID ingelogd. } Nu kunnen
```

2023-06-05 12:34 UTC, Yolijn commented on pages/voorgenomen-huwelijk/getuigen/succes.tsx
> +                    <DataNoTranslate>{partnerContact?.voornaam}</DataNoTranslate> geen broer of zus van je is
```suggestion
                    { voornaam && <><DataNoTranslate>{partnerContact?.voornaam}</DataNoTranslate> geen broer of zus van je is<> : jullie geen broer of zus van elkaar zijn }
```

2023-06-07 16:32 UTC, Robbert approved these changes

2023-06-07 16:33 UTC, merged